config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  
  
  
  root 'initial_pages#home'
  get 'initial_pages/home'
  get '/about_site', to: 'initial_pages#site_about'
  get '/about_team', to: 'initial_pages#team_about'
  get '/signup',     to: 'users#new'
  get '/signup',     to: 'users#create'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
      member do
        get :following, :followers
      end
    end
  resources :contacts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
end

app/controllers/initial_pages_controller.rb
class InitialPagesController < ApplicationController
  def home
    
    if is_logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  
  def about
  end

end

app/helpers/initial_pages_helper.rb
module InitialPagesHelper
end

app/views/initial_pages/home.html.erb
<% if is_logged_in? %>
  <div class="row animated zoomIn">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron animated fadeInDownBig">
    <h1>Welcome to ConnectDev!</h1>
    <p>The app development focused community hub for developers, investors, and entrepreneurs!</p>
    
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well animated fadeInUpBig">
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary btn-block animate shake-horizontal" %>
      </div>
    </div>
    
  </div>
        
  
<% end %>

app/views/initial_pages/site_about.html.erb
<% provide(:title, "About Site") %>
<div class="animated slideInRight">
  <h1>About ConnectDev</h1>
  <p>ConnectDev is an independnt project site written by Cameron Blair.</p>
  <p>The site currently functions as a twitter clone, allowing users to create profiles, post microposts, follow/unfollow users at their own whim.</p>
</div>

app/views/initial_pages/team_about.html.erb
<% provide(:title, "About Team") %>
<div class="animated slideInLeft">
  <h1>About the developer</h1>
  
  <p>Cameron is a web Developer specializing in Ruby on Rails front-end development. Knowledge of numerous programming languages including Ruby with the Rails framework, AngularJS, and ReactJS Strong background in team oriented communication and problem solving. </p>

  <%= link_to  'https://www.linkedin.com/in/cameron-blair-49598b78/' do %>
    <i class='fa fa-linkedin fa-3x slideInLeft' aria-hidden='true'></i>
  <% end %>
</div>