config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  
  
  
  root 'initial_pages#home'
  get 'initial_pages/home'
  get '/about_site', to: 'initial_pages#site_about'
  get '/about_team', to: 'initial_pages#team_about'
  get '/signup',     to: 'users#new'
  get '/signup',     to: 'users#create'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
      member do
        get :following, :followers
      end
    end
  resources :contacts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer animated fadeInUp">
  <small>
    The <%= link_to "ConnectDev", root_path%> App
    by <%= link_to "Cameron Blair", about_team_path%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_site_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ConnectDev", root_path, id: 'logo' %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                  About <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Team", about_team_path %></li>
                <li><%= link_to "Site", about_site_path %></li>
              </ul>
            </li>
            <li><%= link_to "Contact", new_contact_path %></li>
            <% if is_logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divide"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'animate', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
      <![endif]-->
      
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>